import '../../model/chat_model.dart';

List<ChatModel> chatsModels = [
  ChatModel(
    name: 'Osama Nabil',
    icon: 'iconassets/images/person.svg',
    isGroup: false,
    time: '4:00',
    currentMessage: 'Hello Flutter Dev...',
  ),
  ChatModel(
    name: 'Ahmed Salah',
    icon: 'iconassets/images/person.svg',
    isGroup: false,
    time: '2:00',
    currentMessage: 'Hello Flutter Dev...',
  ),
  ChatModel(
    name: 'Ayman Mohammed',
    icon: 'iconassets/images/person.svg',
    isGroup: true,
    time: '4:00',
    currentMessage: 'Hello Flutter Dev...',
  ),
  ChatModel(
    name: 'Seid Khalid',
    icon: 'iconassets/images/person.svg',
    isGroup: false,
    time: '4:00',
    currentMessage: 'Hello Flutter Dev...',
  ),
  ChatModel(
    name: 'Ali Salama',
    icon: 'iconassets/images/person.svg',
    isGroup: true,
    time: '4:00',
    currentMessage: 'Hello Flutter Dev...',
  ),
  ChatModel(
    name: 'Lina Ahmed',
    icon: 'iconassets/images/person.svg',
    isGroup: false,
    time: '3:30',
    currentMessage: 'Hi there!',
  ),
  ChatModel(
    name: 'Sara Hassan',
    icon: 'iconassets/images/person.svg',
    isGroup: false,
    time: '1:15',
    currentMessage: 'How are you?',
  ),
  ChatModel(
    name: 'Team Meeting',
    icon: 'iconassets/images/group.svg',
    isGroup: true,
    time: '10:00',
    currentMessage: "Don't forget our meeting today",
  ),
  ChatModel(
    name: 'Mohammed Ali',
    icon: 'iconassets/images/person.svg',
    isGroup: false,
    time: '5:45',
    currentMessage: "Hey, what's up?",
  ),
  ChatModel(
    name: 'Family Group',
    icon: 'iconassets/images/group.svg',
    isGroup: true,
    time: '8:30',
    currentMessage: 'Good morning, everyone!',
  ),
  ChatModel(
    name: 'Aisha Farid',
    icon: 'iconassets/images/person.svg',
    isGroup: false,
    time: '11:20',
    currentMessage: 'Hello from Aisha!',
  ),
];

List<ChatContactModel> chatContact = [
  ChatContactModel(name: 'Osama', status: 'Be Good Person'),
  ChatContactModel(name: 'Alice', status: 'Busy'),
  ChatContactModel(name: 'Bob', status: 'Away'),
  ChatContactModel(name: 'Charlie', status: 'Online'),
  ChatContactModel(name: 'David', status: 'Offline'),
  ChatContactModel(name: 'Eve', status: 'In a meeting'),
  ChatContactModel(name: 'Frank', status: 'Do Not Disturb'),
  ChatContactModel(name: 'Grace', status: 'Available'),
  ChatContactModel(name: 'Hannah', status: 'On vacation'),
  ChatContactModel(name: 'Isaac', status: 'Sleeping'),
  ChatContactModel(name: 'Julia', status: 'Working'),
  ChatContactModel(name: 'Kevin', status: 'Gaming'),
  ChatContactModel(name: 'Linda', status: 'Eating lunch'),
  ChatContactModel(name: 'Michael', status: 'Watching TV'),
  ChatContactModel(name: 'Nina', status: 'Listening to music'),
];
