// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsUrfHe-o-K526BSP7Ub0RI7vqZbKFUwU',
    appId: '1:606228768094:web:5323eac29f25fac167dbcf',
    messagingSenderId: '606228768094',
    projectId: 'chat-73209',
    authDomain: 'chat-73209.firebaseapp.com',
    storageBucket: 'chat-73209.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL05K-3oQooyiDcxotJekWOsK5rLqG2bM',
    appId: '1:606228768094:android:e005517d0145de9167dbcf',
    messagingSenderId: '606228768094',
    projectId: 'chat-73209',
    storageBucket: 'chat-73209.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWEL1DiHiiyBmLXcibDr4WxgnwZCoDpaI',
    appId: '1:606228768094:ios:c92fffbbf9878eb167dbcf',
    messagingSenderId: '606228768094',
    projectId: 'chat-73209',
    storageBucket: 'chat-73209.appspot.com',
    iosClientId: '606228768094-npvq511obk4jd1a83g6f7miqjfbhiv5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWEL1DiHiiyBmLXcibDr4WxgnwZCoDpaI',
    appId: '1:606228768094:ios:58873dd30d3b64ab67dbcf',
    messagingSenderId: '606228768094',
    projectId: 'chat-73209',
    storageBucket: 'chat-73209.appspot.com',
    iosClientId: '606228768094-4fo6rt606stbkgg10nbvig5tj6dmbot8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
